### ISSUE TITLE
BUG: precached git directory might be corrupted

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#350] opened 2023-11-01 01:37 UTC
Example:
```
    today at 3:34:39 AM11/01/2023 01:34:39 AM UTC [INFO] Listening for new trigger events
    today at 3:34:39 AM11/01/2023 01:34:39 AM UTC [INFO] Press Ctrl-C to stop.
    today at 3:34:43 AM11/01/2023 01:34:43 AM UTC [INFO] Updating repo for kernelci_staging-next
    today at 3:35:00 AMFrom https://github.com/kernelci/linux
    today at 3:35:00 AM + 36efabe4fc1d...ea2ec3e91789 chromeos-stable            -> kernelci/chromeos-stable  (forced update)
    today at 3:35:00 AM + c04111fedb77...81c233ba7452 linux-6.1.y-arm64-chromeos -> kernelci/linux-6.1.y-arm64-chromeos  (forced update)
    today at 3:35:03 AM + 092757607e40...bb1ee218d02a staging-next               -> kernelci/staging-next  (forced update)
    today at 3:35:03 AM + 8924cd217361...f463d3a4ed06 staging-stable             -> kernelci/staging-stable  (forced update)
    today at 3:35:03 AM * [new tag]                   chromeos-stable-20231031.1 -> chromeos-stable-20231031.1
    today at 3:35:03 AM * [new tag]                   linux-6.1.y-arm64-chromeos-20231031.1 -> linux-6.1.y-arm64-chromeos-20231031.1
    today at 3:35:03 AM * [new tag]                   staging-next-20231101.0    -> staging-next-20231101.0
    today at 3:35:03 AM * [new tag]                   staging-stable-20231101.0  -> staging-stable-20231101.0
    today at 3:35:09 AMFrom https://github.com/kernelci/linux
    today at 3:35:09 AM * branch                      HEAD       -> FETCH_HEAD
    today at 3:35:14 AMFrom git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux
    today at 3:35:14 AM * branch                      HEAD       -> FETCH_HEAD
    today at 3:35:14 AMfatal: Unable to create '/home/kernelci/data/src/linux/.git/index.lock': File exists.
    today at 3:35:14 AM
    today at 3:35:14 AMAnother git process seems to be running in this repository, e.g.
    today at 3:35:14 AMan editor opened by 'git commit'. Please make sure all processes
    today at 3:35:14 AMare terminated then try again. If it still fails, a git process
    today at 3:35:14 AMmay have crashed in this repository earlier:
    today at 3:35:14 AMremove the file manually to continue.
    today at 3:35:14 AM11/01/2023 01:35:14 AM UTC [ERROR] Traceback (most recent call last):
    today at 3:35:14 AM  File "/home/kernelci/pipeline/base.py", line 69, in run
    today at 3:35:14 AM    status = self._run(context)
    today at 3:35:14 AM  File "/home/kernelci/./pipeline/tarball.py", line 136, in _run
    today at 3:35:14 AM    self._update_repo(build_config)
    today at 3:35:14 AM  File "/home/kernelci/./pipeline/tarball.py", line 59, in _update_repo
    today at 3:35:14 AM    kernelci.build.update_repo(config, self._kdir)
    today at 3:35:14 AM  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/build.py", line 163, in update_repo
    today at 3:35:14 AM    shell_cmd("""
    today at 3:35:14 AM  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/__init__.py", line 29, in shell_cmd
    today at 3:35:14 AM    return subprocess.check_output(cmd, shell=True).decode()
    today at 3:35:14 AM  File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
    today at 3:35:14 AM    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    today at 3:35:14 AM  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    today at 3:35:14 AM    raise CalledProcessError(retcode, process.args,
    today at 3:35:14 AMsubprocess.CalledProcessError: Command '
    today at 3:35:14 AMset -e
    today at 3:35:14 AMcd /home/kernelci/data/src/linux
    today at 3:35:14 AMgit reset --hard
    today at 3:35:14 AMgit clean -fd
    today at 3:35:14 AMgit checkout --detach kernelci/staging-next
    today at 3:35:14 AM' returned non-zero exit status 128.
    today at 3:35:14 AM
    today at 3:35:14 AMContainer stopped
```
In case of such failures probably it will be logical to force-delete directory and do "fresh" git clone.

**Comment by gctucker** [comment] 2023-11-01 14:14
Is this while creating a tarball?  I think it should be turned into a job like kunit and kbuild and run in Kubernetes but with a volume to avoid doing full checkouts every time.  It could then use a Git mirror to actually checkout the code from scratch every time but not the whole Git meta-data.

**Comment by JenySadadia** [comment] 2023-12-29 06:46
Duplicate of https://github.com/kernelci/kernelci-pipeline/issues/361

**Closed by JenySadadia** 2023-12-29 06:46 UTC
